server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/map_db?serverTimezone=America/New_York&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: "xxxxxxx"
  # redis:
  #   host: localhost
  #   port: 6379
  #   password: 123456
  #   database: 0

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.map.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      map:
        mapper: debug
        service: info
        controller: info